# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 07:52
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='\u7ae0\u8282\u540d')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('parentChapter_ID', models.IntegerField(blank=True, verbose_name='\u7236\u7ae0\u8282id')),
                ('sonChapters_ID', models.TextField(verbose_name='\u5b50\u7ae0\u8282id')),
                ('son_num', models.IntegerField(default=0, verbose_name='\u5b50\u7ae0\u8282\u6570\u91cf')),
                ('image_url', models.URLField(blank=True, verbose_name='\u56fe\u7247\u94fe\u63a5')),
                ('enjoy_num', models.IntegerField(default=0, verbose_name='\u559c\u6b22\u4eba\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='\u6545\u4e8b\u540d')),
                ('son_num', models.IntegerField(default=0, verbose_name='\u5b50\u7ae0\u8282\u6570\u91cf')),
                ('enjoy_num', models.IntegerField(default=0, verbose_name='\u559c\u6b22\u4eba\u6570')),
                ('part_in_num', models.IntegerField(default=0, verbose_name='\u53c2\u4e0e\u521b\u4f5c\u4eba\u6570')),
                ('headchapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.Chapter', verbose_name='\u542f\u52a8\u7ae0\u8282')),
            ],
        ),
        migrations.CreateModel(
            name='StoUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('power', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='start_author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.StoUser'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.StoUser', verbose_name='\u521b\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='lovers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u559c\u6b22\u7684\u4eba'),
        ),
    ]
